### ISSUE TITLE
[Xamarin.Android] Destroy/Delete endpoint crash on Android 9.0

### ISSUE THREAD

**Issue by ngkien1530** [pjsip/testproject10#2184]
I'm facing a issue which cause the xamarin android app to crash only on Android 9.0 (API 28) when destroying the endpoint
`sipEndPoint.libDestroy();`

I complie the PJSIP library (with TLS config) for xamarin android using:
OpenSSL 1.0.2h  / 1.1.1.c 
Android NDK r10e / r17b
Pjproject-2.8 / 2.9

Here is my stack-trace:
https://www.pastiebin.com/5d566a33d8bbe

Using Xamarin 3.2 on VS2017
Thank you for your help.

**Comment by ismangil** [comment]
This is a test repo, please report issues to the mailing list instead.
